swagger: '2.0'
info:
  title: HACKED BY RAGHAV
  description: /><marquee></h1>HACKED BY RAGHAV</h1></marquee><!--
  version: production
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
