swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: </div></p><a/href='javascript:alert(1)'>Click Me</a>
  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
